/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendeeRouteImport } from './routes/_attendee'
import { Route as OrganizerRouteImport } from './routes/_organizer'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as OrganizerDashboardRouteImport } from './routes/_organizer/dashboard'
import { Route as StaffScanRouteImport } from './routes/_staff/scan'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as BrowseEventIdRouteImport } from './routes/browse/$eventId'
import { Route as BrowseConfirmationRouteImport } from './routes/browse/confirmation'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AttendeeTicketsIndexRouteImport } from './routes/_attendee/tickets/index'
import { Route as AttendeeTicketsTicketIdRouteImport } from './routes/_attendee/tickets/$ticketId'
import { Route as OrganizerEventsIndexRouteImport } from './routes/_organizer/events/index'
import { Route as OrganizerEventsEventIdRouteImport } from './routes/_organizer/events/$eventId'
import { Route as OrganizerEventsNewRouteImport } from './routes/_organizer/events/new'
import { Route as OrganizerVenuesIndexRouteImport } from './routes/_organizer/venues/index'
import { Route as OrganizerVenuesVenueIdRouteImport } from './routes/_organizer/venues/$venueId'
import { Route as OrganizerVenuesNewRouteImport } from './routes/_organizer/venues/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeRoute = AttendeeRouteImport.update({
  id: '/_attendee',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/_organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizerRoute,
} as any)
const StaffScanRoute = StaffScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StaffRoute,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseEventIdRoute = BrowseEventIdRouteImport.update({
  id: '/browse/$eventId',
  path: '/browse/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseConfirmationRoute = BrowseConfirmationRouteImport.update({
  id: '/browse/confirmation',
  path: '/browse/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeTicketsIndexRoute = AttendeeTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AttendeeRoute,
} as any)
const AttendeeTicketsTicketIdRoute = AttendeeTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AttendeeRoute,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEventsEventIdRoute = OrganizerEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesIndexRoute = OrganizerVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesVenueIdRoute = OrganizerVenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesNewRoute = OrganizerVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => OrganizerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof OrganizerDashboardRoute
  '/scan': typeof StaffScanRoute
  '/browse/$eventId': typeof BrowseEventIdRoute
  '/browse/confirmation': typeof BrowseConfirmationRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/browse/': typeof BrowseIndexRoute
  '/tickets/$ticketId': typeof AttendeeTicketsTicketIdRoute
  '/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/new': typeof OrganizerEventsNewRoute
  '/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/venues/new': typeof OrganizerVenuesNewRoute
  '/tickets/': typeof AttendeeTicketsIndexRoute
  '/events/': typeof OrganizerEventsIndexRoute
  '/venues/': typeof OrganizerVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof OrganizerDashboardRoute
  '/scan': typeof StaffScanRoute
  '/browse/$eventId': typeof BrowseEventIdRoute
  '/browse/confirmation': typeof BrowseConfirmationRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/browse': typeof BrowseIndexRoute
  '/tickets/$ticketId': typeof AttendeeTicketsTicketIdRoute
  '/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/new': typeof OrganizerEventsNewRoute
  '/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/venues/new': typeof OrganizerVenuesNewRoute
  '/tickets': typeof AttendeeTicketsIndexRoute
  '/events': typeof OrganizerEventsIndexRoute
  '/venues': typeof OrganizerVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_attendee': typeof AttendeeRouteWithChildren
  '/_organizer': typeof OrganizerRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/_organizer/dashboard': typeof OrganizerDashboardRoute
  '/_staff/scan': typeof StaffScanRoute
  '/browse/$eventId': typeof BrowseEventIdRoute
  '/browse/confirmation': typeof BrowseConfirmationRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/browse/': typeof BrowseIndexRoute
  '/_attendee/tickets/$ticketId': typeof AttendeeTicketsTicketIdRoute
  '/_organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/_organizer/events/new': typeof OrganizerEventsNewRoute
  '/_organizer/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/_organizer/venues/new': typeof OrganizerVenuesNewRoute
  '/_attendee/tickets/': typeof AttendeeTicketsIndexRoute
  '/_organizer/events/': typeof OrganizerEventsIndexRoute
  '/_organizer/venues/': typeof OrganizerVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/dashboard'
    | '/scan'
    | '/browse/$eventId'
    | '/browse/confirmation'
    | '/demo/tanstack-query'
    | '/browse/'
    | '/tickets/$ticketId'
    | '/events/$eventId'
    | '/events/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/tickets/'
    | '/events/'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/dashboard'
    | '/scan'
    | '/browse/$eventId'
    | '/browse/confirmation'
    | '/demo/tanstack-query'
    | '/browse'
    | '/tickets/$ticketId'
    | '/events/$eventId'
    | '/events/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/tickets'
    | '/events'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_attendee'
    | '/_organizer'
    | '/_staff'
    | '/about'
    | '/callback'
    | '/_organizer/dashboard'
    | '/_staff/scan'
    | '/browse/$eventId'
    | '/browse/confirmation'
    | '/demo/tanstack-query'
    | '/browse/'
    | '/_attendee/tickets/$ticketId'
    | '/_organizer/events/$eventId'
    | '/_organizer/events/new'
    | '/_organizer/venues/$venueId'
    | '/_organizer/venues/new'
    | '/_attendee/tickets/'
    | '/_organizer/events/'
    | '/_organizer/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendeeRoute: typeof AttendeeRouteWithChildren
  OrganizerRoute: typeof OrganizerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  BrowseEventIdRoute: typeof BrowseEventIdRoute
  BrowseConfirmationRoute: typeof BrowseConfirmationRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_attendee': {
      id: '/_attendee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AttendeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer': {
      id: '/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer/dashboard': {
      id: '/_organizer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_staff/scan': {
      id: '/_staff/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof StaffScanRouteImport
      parentRoute: typeof StaffRoute
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$eventId': {
      id: '/browse/$eventId'
      path: '/browse/$eventId'
      fullPath: '/browse/$eventId'
      preLoaderRoute: typeof BrowseEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/confirmation': {
      id: '/browse/confirmation'
      path: '/browse/confirmation'
      fullPath: '/browse/confirmation'
      preLoaderRoute: typeof BrowseConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_attendee/tickets/': {
      id: '/_attendee/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AttendeeTicketsIndexRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/_attendee/tickets/$ticketId': {
      id: '/_attendee/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AttendeeTicketsTicketIdRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/_organizer/events/': {
      id: '/_organizer/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/events/$eventId': {
      id: '/_organizer/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof OrganizerEventsEventIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/events/new': {
      id: '/_organizer/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/': {
      id: '/_organizer/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof OrganizerVenuesIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/$venueId': {
      id: '/_organizer/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof OrganizerVenuesVenueIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/new': {
      id: '/_organizer/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof OrganizerVenuesNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
  }
}

interface AttendeeRouteChildren {
  AttendeeTicketsTicketIdRoute: typeof AttendeeTicketsTicketIdRoute
  AttendeeTicketsIndexRoute: typeof AttendeeTicketsIndexRoute
}

const AttendeeRouteChildren: AttendeeRouteChildren = {
  AttendeeTicketsTicketIdRoute: AttendeeTicketsTicketIdRoute,
  AttendeeTicketsIndexRoute: AttendeeTicketsIndexRoute,
}

const AttendeeRouteWithChildren = AttendeeRoute._addFileChildren(
  AttendeeRouteChildren,
)

interface OrganizerRouteChildren {
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerEventsEventIdRoute: typeof OrganizerEventsEventIdRoute
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  OrganizerVenuesVenueIdRoute: typeof OrganizerVenuesVenueIdRoute
  OrganizerVenuesNewRoute: typeof OrganizerVenuesNewRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
  OrganizerVenuesIndexRoute: typeof OrganizerVenuesIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerEventsEventIdRoute: OrganizerEventsEventIdRoute,
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  OrganizerVenuesVenueIdRoute: OrganizerVenuesVenueIdRoute,
  OrganizerVenuesNewRoute: OrganizerVenuesNewRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
  OrganizerVenuesIndexRoute: OrganizerVenuesIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface StaffRouteChildren {
  StaffScanRoute: typeof StaffScanRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffScanRoute: StaffScanRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendeeRoute: AttendeeRouteWithChildren,
  OrganizerRoute: OrganizerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  BrowseEventIdRoute: BrowseEventIdRoute,
  BrowseConfirmationRoute: BrowseConfirmationRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
