/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendeeRouteImport } from './routes/_attendee'
import { Route as OrganizerRouteImport } from './routes/_organizer'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AttendeeBrowseRouteImport } from './routes/_attendee/browse'
import { Route as OrganizerDashboardRouteImport } from './routes/_organizer/dashboard'
import { Route as StaffScanRouteImport } from './routes/_staff/scan'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as OrganizerEventsIndexRouteImport } from './routes/_organizer/events/index'
import { Route as OrganizerEventsNewRouteImport } from './routes/_organizer/events/new'
import { Route as OrganizerVenuesIndexRouteImport } from './routes/_organizer/venues/index'
import { Route as OrganizerVenuesVenueIdRouteImport } from './routes/_organizer/venues/$venueId'
import { Route as OrganizerVenuesNewRouteImport } from './routes/_organizer/venues/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeRoute = AttendeeRouteImport.update({
  id: '/_attendee',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/_organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeBrowseRoute = AttendeeBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AttendeeRoute,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizerRoute,
} as any)
const StaffScanRoute = StaffScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StaffRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesIndexRoute = OrganizerVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesVenueIdRoute = OrganizerVenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerVenuesNewRoute = OrganizerVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => OrganizerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/browse': typeof AttendeeBrowseRoute
  '/dashboard': typeof OrganizerDashboardRoute
  '/scan': typeof StaffScanRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/new': typeof OrganizerEventsNewRoute
  '/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/venues/new': typeof OrganizerVenuesNewRoute
  '/events/': typeof OrganizerEventsIndexRoute
  '/venues/': typeof OrganizerVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/browse': typeof AttendeeBrowseRoute
  '/dashboard': typeof OrganizerDashboardRoute
  '/scan': typeof StaffScanRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/new': typeof OrganizerEventsNewRoute
  '/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/venues/new': typeof OrganizerVenuesNewRoute
  '/events': typeof OrganizerEventsIndexRoute
  '/venues': typeof OrganizerVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_attendee': typeof AttendeeRouteWithChildren
  '/_organizer': typeof OrganizerRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/_attendee/browse': typeof AttendeeBrowseRoute
  '/_organizer/dashboard': typeof OrganizerDashboardRoute
  '/_staff/scan': typeof StaffScanRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_organizer/events/new': typeof OrganizerEventsNewRoute
  '/_organizer/venues/$venueId': typeof OrganizerVenuesVenueIdRoute
  '/_organizer/venues/new': typeof OrganizerVenuesNewRoute
  '/_organizer/events/': typeof OrganizerEventsIndexRoute
  '/_organizer/venues/': typeof OrganizerVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/browse'
    | '/dashboard'
    | '/scan'
    | '/demo/tanstack-query'
    | '/events/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/events/'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/browse'
    | '/dashboard'
    | '/scan'
    | '/demo/tanstack-query'
    | '/events/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/events'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_attendee'
    | '/_organizer'
    | '/_staff'
    | '/about'
    | '/callback'
    | '/_attendee/browse'
    | '/_organizer/dashboard'
    | '/_staff/scan'
    | '/demo/tanstack-query'
    | '/_organizer/events/new'
    | '/_organizer/venues/$venueId'
    | '/_organizer/venues/new'
    | '/_organizer/events/'
    | '/_organizer/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendeeRoute: typeof AttendeeRouteWithChildren
  OrganizerRoute: typeof OrganizerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_attendee': {
      id: '/_attendee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AttendeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer': {
      id: '/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_attendee/browse': {
      id: '/_attendee/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AttendeeBrowseRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/_organizer/dashboard': {
      id: '/_organizer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_staff/scan': {
      id: '/_staff/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof StaffScanRouteImport
      parentRoute: typeof StaffRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organizer/events/': {
      id: '/_organizer/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/events/new': {
      id: '/_organizer/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/': {
      id: '/_organizer/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof OrganizerVenuesIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/$venueId': {
      id: '/_organizer/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof OrganizerVenuesVenueIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/_organizer/venues/new': {
      id: '/_organizer/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof OrganizerVenuesNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
  }
}

interface AttendeeRouteChildren {
  AttendeeBrowseRoute: typeof AttendeeBrowseRoute
}

const AttendeeRouteChildren: AttendeeRouteChildren = {
  AttendeeBrowseRoute: AttendeeBrowseRoute,
}

const AttendeeRouteWithChildren = AttendeeRoute._addFileChildren(
  AttendeeRouteChildren,
)

interface OrganizerRouteChildren {
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  OrganizerVenuesVenueIdRoute: typeof OrganizerVenuesVenueIdRoute
  OrganizerVenuesNewRoute: typeof OrganizerVenuesNewRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
  OrganizerVenuesIndexRoute: typeof OrganizerVenuesIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  OrganizerVenuesVenueIdRoute: OrganizerVenuesVenueIdRoute,
  OrganizerVenuesNewRoute: OrganizerVenuesNewRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
  OrganizerVenuesIndexRoute: OrganizerVenuesIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface StaffRouteChildren {
  StaffScanRoute: typeof StaffScanRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffScanRoute: StaffScanRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendeeRoute: AttendeeRouteWithChildren,
  OrganizerRoute: OrganizerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
